import 'package:flutter/material.dart';
import 'package:minddy/generated/l10n.dart';

class IconInfo {
  int iconId;
  String category;
  List<String> tags;
  IconData icon;

  IconInfo({required this.icon, required this.category, required this.tags, required this.iconId});
}

class PluginUiComponentIconIcons {
  static List<IconInfo> icons = [
    IconInfo(icon: Icons.abc, category: S.current.icons_category_text, tags: [S.current.icons_tags_alphabet, S.current.icons_tags_letters], iconId: 1),
    IconInfo(icon: Icons.access_alarm_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_alarm, S.current.icons_tags_clock, S.current.icons_category_time], iconId: 2),
    IconInfo(icon: Icons.anchor, category: S.current.icons_category_transport, tags: [S.current.icons_tags_anchor, S.current.icons_tags_boat], iconId: 4),
    IconInfo(icon: Icons.battery_charging_full_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_battery, S.current.icons_tags_charging], iconId: 6),
    IconInfo(icon: Icons.bluetooth_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_bluetooth, S.current.icons_tags_wireless], iconId: 8),
    IconInfo(icon: Icons.book_rounded, category: S.current.icons_category_education, tags: [S.current.icons_tags_book, S.current.icons_tags_reading], iconId: 9),
    IconInfo(icon: Icons.brush_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_art, S.current.icons_tags_paint], iconId: 10),
    IconInfo(icon: Icons.camera_alt_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_camera, S.current.icons_tags_photo], iconId: 12),
    IconInfo(icon: Icons.car_rental_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_car, S.current.icons_tags_rental], iconId: 13),
    IconInfo(icon: Icons.chat_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_chat, S.current.icons_tags_message], iconId: 14),
    IconInfo(icon: Icons.cloud_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_cloud, S.current.icons_category_weather], iconId: 15),
    IconInfo(icon: Icons.computer_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_computer, S.current.icons_tags_laptop], iconId: 16),
    IconInfo(icon: Icons.construction_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_construction, S.current.icons_category_tools], iconId: 17),
    IconInfo(icon: Icons.directions_bike_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_bike, S.current.icons_tags_cycling], iconId: 18),
    IconInfo(icon: Icons.directions_boat_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_boat, S.current.icons_tags_water], iconId: 19),
    IconInfo(icon: Icons.directions_bus_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_bus, S.current.icons_tags_public_transport], iconId: 20),
    IconInfo(icon: Icons.directions_car_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_car, S.current.icons_tags_vehicle], iconId: 21),
    IconInfo(icon: Icons.directions_railway_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_train, S.current.icons_tags_rail], iconId: 22),
    IconInfo(icon: Icons.directions_run_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_running, S.current.icons_tags_exercise], iconId: 23),
    IconInfo(icon: Icons.directions_subway_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_subway, S.current.icons_tags_metro], iconId: 24),
    IconInfo(icon: Icons.directions_walk_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_walking, S.current.icons_tags_hiking], iconId: 25),
    IconInfo(icon: Icons.email_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_email, S.current.icons_tags_message], iconId: 26),
    IconInfo(icon: Icons.fastfood_rounded, category: S.current.icons_category_food, tags: [S.current.icons_tags_fast_food, S.current.icons_tags_meal], iconId: 27),
    IconInfo(icon: Icons.favorite_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_like, S.current.icons_tags_heart], iconId: 28),
    IconInfo(icon: Icons.flight_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_flight, S.current.icons_category_travel], iconId: 29),
    IconInfo(icon: Icons.forum_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_forum, S.current.icons_tags_discussion], iconId: 30),
    IconInfo(icon: Icons.games_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_games, S.current.icons_tags_play], iconId: 31),
    IconInfo(icon: Icons.headphones_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_headphones, S.current.icons_tags_audio], iconId: 32),
    IconInfo(icon: Icons.home_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_category_home, S.current.icons_tags_house], iconId: 33),
    IconInfo(icon: Icons.hotel_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_hotel, S.current.icons_tags_stay], iconId: 34),
    IconInfo(icon: Icons.image_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_image, S.current.icons_tags_photo], iconId: 35),
    IconInfo(icon: Icons.keyboard_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_keyboard, S.current.icons_tags_input], iconId: 36),
    IconInfo(icon: Icons.kitchen_rounded, category: S.current.icons_category_food, tags: [S.current.icons_category_kitchen, S.current.icons_tags_cooking], iconId: 37),
    IconInfo(icon: Icons.lightbulb_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_light, S.current.icons_tags_idea], iconId: 38),
    IconInfo(icon: Icons.local_cafe_rounded, category: S.current.icons_category_food, tags: [S.current.icons_tags_cafe, S.current.icons_tags_coffee], iconId: 39),
    IconInfo(icon: Icons.local_dining_rounded, category: S.current.icons_category_food, tags: [S.current.icons_tags_dining, S.current.icons_tags_restaurant], iconId: 40),
    IconInfo(icon: Icons.local_florist_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_florist, S.current.icons_tags_flowers], iconId: 41),
    IconInfo(icon: Icons.lock_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_lock, S.current.icons_tags_security], iconId: 42),
    IconInfo(icon: Icons.map_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_map, S.current.icons_category_location], iconId: 43),
    IconInfo(icon: Icons.message_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_message, S.current.icons_tags_chat], iconId: 44),
    IconInfo(icon: Icons.mic_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_microphone, S.current.icons_tags_audio], iconId: 45),
    IconInfo(icon: Icons.motorcycle_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_motorcycle, S.current.icons_tags_bike], iconId: 46),
    IconInfo(icon: Icons.music_note_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_music, S.current.icons_tags_note], iconId: 47),
    IconInfo(icon: Icons.nature_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_category_nature, S.current.icons_tags_outdoors], iconId: 48),
    IconInfo(icon: Icons.navigation_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_category_navigation, S.current.icons_tags_directions], iconId: 49),
    IconInfo(icon: Icons.network_wifi_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_wifi, S.current.icons_tags_internet], iconId: 50),
    IconInfo(icon: Icons.phone_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_phone, S.current.icons_tags_call], iconId: 51),
    IconInfo(icon: Icons.photo_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_photo, S.current.icons_tags_image], iconId: 52),
    IconInfo(icon: Icons.place_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_place, S.current.icons_category_location], iconId: 53),
    IconInfo(icon: Icons.print_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_printer, S.current.icons_tags_print], iconId: 54),
    IconInfo(icon: Icons.public_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_public, S.current.icons_tags_place], iconId: 55),
    IconInfo(icon: Icons.restaurant_rounded, category: S.current.icons_category_food, tags: [S.current.icons_tags_restaurant, S.current.icons_tags_dining], iconId: 56),
    IconInfo(icon: Icons.router_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_router, S.current.icons_tags_network], iconId: 57),
    IconInfo(icon: Icons.rowing_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_rowing, S.current.icons_tags_water], iconId: 58),
    IconInfo(icon: Icons.save_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_save, S.current.icons_tags_file], iconId: 59),
    IconInfo(icon: Icons.school_rounded, category: S.current.icons_category_education, tags: [S.current.icons_tags_school, S.current.icons_tags_learning], iconId: 60),
    IconInfo(icon: Icons.send_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_send, S.current.icons_tags_message], iconId: 61),
    IconInfo(icon: Icons.settings_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_settings, S.current.icons_tags_preferences], iconId: 62),
    IconInfo(icon: Icons.share_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_share, S.current.icons_category_social], iconId: 63),
    IconInfo(icon: Icons.shopping_cart_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_shopping, S.current.icons_tags_cart], iconId: 64),
    IconInfo(icon: Icons.smartphone_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_smartphone, S.current.icons_tags_mobile], iconId: 65),
    IconInfo(icon: Icons.snowboarding_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_snowboarding, S.current.icons_tags_sports], iconId: 66),
    IconInfo(icon: Icons.spa_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_spa, S.current.icons_tags_relaxation], iconId: 67),
    IconInfo(icon: Icons.speaker_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_speaker, S.current.icons_tags_audio], iconId: 68),
    IconInfo(icon: Icons.star_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_star, S.current.icons_tags_favorite], iconId: 69),
    IconInfo(icon: Icons.store_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_store, S.current.icons_tags_shopping], iconId: 70),
    IconInfo(icon: Icons.subway_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_subway, S.current.icons_tags_train], iconId: 71),
    IconInfo(icon: Icons.wb_sunny_outlined, category: S.current.icons_category_nature, tags: [S.current.icons_tags_sunny, S.current.icons_category_weather], iconId: 72),
    IconInfo(icon: Icons.support_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_support, S.current.icons_tags_help], iconId: 73),
    IconInfo(icon: Icons.terrain_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_terrain, S.current.icons_tags_landscape], iconId: 74),
    IconInfo(icon: Icons.thermostat_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_thermostat, S.current.icons_tags_temperature], iconId: 75),
    IconInfo(icon: Icons.thumb_up_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_thumb, S.current.icons_tags_like], iconId: 76),
    IconInfo(icon: Icons.train_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_train, S.current.icons_category_transport], iconId: 77),
    IconInfo(icon: Icons.traffic_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_traffic, S.current.icons_tags_road], iconId: 78),
    IconInfo(icon: Icons.transit_enterexit_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_transit, S.current.icons_category_transport], iconId: 79),
    IconInfo(icon: Icons.tv_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_tv, S.current.icons_tags_television], iconId: 80),
    IconInfo(icon: Icons.umbrella_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_umbrella, S.current.icons_tags_rain], iconId: 81),
    IconInfo(icon: Icons.usb_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_usb, S.current.icons_tags_connection], iconId: 82),
    IconInfo(icon: Icons.videocam_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_video, S.current.icons_tags_camera], iconId: 83),
    IconInfo(icon: Icons.volume_up_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_volume, S.current.icons_tags_sound], iconId: 84),
    IconInfo(icon: Icons.watch_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_watch, S.current.icons_category_time], iconId: 85),
    IconInfo(icon: Icons.waves_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_waves, S.current.icons_tags_water], iconId: 86),
    IconInfo(icon: Icons.wb_cloudy_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_cloudy, S.current.icons_category_weather], iconId: 87),
    IconInfo(icon: Icons.web_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_web, S.current.icons_tags_internet], iconId: 88),
    IconInfo(icon: Icons.wifi_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_wifi, S.current.icons_tags_wireless], iconId: 89),
    IconInfo(icon: Icons.work_rounded, category: S.current.icons_category_social, tags: [S.current.icons_tags_work, S.current.icons_tags_job], iconId: 90),
    IconInfo(icon: Icons.yard_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_yard, S.current.icons_tags_outdoor], iconId: 91),
    IconInfo(icon: Icons.zoom_in_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_zoom, S.current.icons_tags_magnify], iconId: 92),
    IconInfo(icon: Icons.zoom_out_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_zoom, S.current.icons_tags_reduce], iconId: 93),
    IconInfo(icon: Icons.add_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_add, S.current.icons_tags_plus], iconId: 94),
    IconInfo(icon: Icons.delete_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_delete, S.current.icons_tags_remove], iconId: 95),
    IconInfo(icon: Icons.edit_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_edit, S.current.icons_tags_modify], iconId: 96),
    IconInfo(icon: Icons.check_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_check, S.current.icons_tags_confirm], iconId: 97),
    IconInfo(icon: Icons.close_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_close, S.current.icons_tags_cancel], iconId: 98),
    IconInfo(icon: Icons.menu_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_menu, S.current.icons_category_navigation], iconId: 99),
    IconInfo(icon: Icons.more_vert_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_more, S.current.icons_tags_options], iconId: 100),
    IconInfo(icon: Icons.accessibility_new_rounded, category: S.current.icons_category_accessibility, tags: [S.current.icons_category_accessibility, S.current.icons_tags_wheelchair], iconId: 101),
    IconInfo(icon: Icons.account_balance_rounded, category: S.current.icons_category_finance, tags: [S.current.icons_tags_account, S.current.icons_tags_balance, S.current.icons_tags_bank], iconId: 102),
    IconInfo(icon: Icons.account_circle_rounded, category: S.current.icons_category_user, tags: [S.current.icons_tags_account, S.current.icons_tags_profile, S.current.icons_category_user], iconId: 103),
    IconInfo(icon: Icons.add_a_photo_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_add, S.current.icons_tags_photo, S.current.icons_tags_camera], iconId: 104),
    IconInfo(icon: Icons.add_alarm_rounded, category: S.current.icons_category_time, tags: [S.current.icons_tags_add, S.current.icons_tags_alarm, S.current.icons_tags_clock], iconId: 105),
    IconInfo(icon: Icons.add_alert_rounded, category: S.current.icons_category_notification, tags: [S.current.icons_tags_add, S.current.icons_category_notification], iconId: 106),
    IconInfo(icon: Icons.add_box_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_add, S.current.icons_tags_new], iconId: 107),
    IconInfo(icon: Icons.add_business_rounded, category: S.current.icons_category_business, tags: [S.current.icons_tags_add, S.current.icons_category_business, S.current.icons_tags_store], iconId: 108),
    IconInfo(icon: Icons.add_ic_call_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_add, S.current.icons_tags_call, S.current.icons_tags_phone], iconId: 109),
    IconInfo(icon: Icons.add_chart_rounded, category: S.current.icons_category_data, tags: [S.current.icons_tags_add, S.current.icons_tags_chart], iconId: 110),
    IconInfo(icon: Icons.add_location_rounded, category: S.current.icons_category_location, tags: [S.current.icons_tags_add, S.current.icons_category_location, S.current.icons_tags_map], iconId: 111),
    IconInfo(icon: Icons.add_moderator_rounded, category: S.current.icons_category_moderation, tags: [S.current.icons_tags_add, S.current.icons_tags_control], iconId: 112),
    IconInfo(icon: Icons.add_to_home_screen_rounded, category: S.current.icons_category_home, tags: [S.current.icons_tags_add, S.current.icons_category_home, S.current.icons_tags_screen], iconId: 113),
    IconInfo(icon: Icons.agriculture_rounded, category: S.current.icons_category_nature, tags: [S.current.icons_tags_farm], iconId: 114),
    IconInfo(icon: Icons.air_rounded, category: S.current.icons_category_weather, tags: [S.current.icons_tags_air, S.current.icons_category_weather], iconId: 115),
    IconInfo(icon: Icons.airline_seat_flat_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_seat], iconId: 116),
    IconInfo(icon: Icons.airline_seat_individual_suite_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_individual, S.current.icons_tags_suite], iconId: 117),
    IconInfo(icon: Icons.airline_seat_legroom_extra_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_legroom], iconId: 118),
    IconInfo(icon: Icons.airline_seat_legroom_normal_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_legroom], iconId: 119),
    IconInfo(icon: Icons.airline_seat_legroom_reduced_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_legroom], iconId: 120),
    IconInfo(icon: Icons.airline_seat_recline_extra_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_recline], iconId: 121),
    IconInfo(icon: Icons.airline_seat_recline_normal_rounded, category: S.current.icons_category_transport, tags: [S.current.icons_tags_airline, S.current.icons_tags_recline], iconId: 122),
    IconInfo(icon: Icons.alarm_add_rounded, category: S.current.icons_category_time, tags: [S.current.icons_tags_alarm, S.current.icons_tags_add], iconId: 123),
    IconInfo(icon: Icons.alarm_off_rounded, category: S.current.icons_category_time, tags: [S.current.icons_tags_alarm, S.current.icons_tags_off], iconId: 124),
    IconInfo(icon: Icons.alarm_on_rounded, category: S.current.icons_category_time, tags: [S.current.icons_tags_alarm, S.current.icons_tags_on], iconId: 125),
    IconInfo(icon: Icons.album_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_music, S.current.icons_tags_music], iconId: 126),
    IconInfo(icon: Icons.all_inbox_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_all, S.current.icons_tags_inbox], iconId: 127),
    IconInfo(icon: Icons.all_out_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_all, S.current.icons_tags_out], iconId: 128),
    IconInfo(icon: Icons.arrow_back_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_back], iconId: 129),
    IconInfo(icon: Icons.arrow_back_ios_new_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_back, S.current.icons_tags_ios], iconId: 130),
    IconInfo(icon: Icons.arrow_circle_down_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_circle, S.current.icons_tags_down], iconId: 131),
    IconInfo(icon: Icons.arrow_circle_up_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_circle, S.current.icons_tags_up], iconId: 132),
    IconInfo(icon: Icons.arrow_forward_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_forward], iconId: 133),
    IconInfo(icon: Icons.arrow_forward_ios_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_forward, S.current.icons_tags_ios], iconId: 134),
    IconInfo(icon: Icons.arrow_right_alt_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_right, S.current.icons_tags_alt], iconId: 135),
    IconInfo(icon: Icons.arrow_upward_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_arrow, S.current.icons_tags_upward], iconId: 136),
    IconInfo(icon: Icons.article_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_article, S.current.icons_tags_document], iconId: 137),
    IconInfo(icon: Icons.aspect_ratio_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_aspect, S.current.icons_tags_ratio], iconId: 138),
    IconInfo(icon: Icons.assessment_rounded, category: S.current.icons_category_data, tags: [S.current.icons_tags_assessment, S.current.icons_tags_report], iconId: 139),
    IconInfo(icon: Icons.assignment_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_assignment, S.current.icons_tags_task], iconId: 140),
    IconInfo(icon: Icons.assignment_turned_in_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_assignment, S.current.icons_tags_turned, S.current.icons_tags_in], iconId: 141),
    IconInfo(icon: Icons.assistant_rounded, category: S.current.icons_category_user, tags: [S.current.icons_tags_assistant, S.current.icons_tags_help], iconId: 142),
    IconInfo(icon: Icons.assistant_direction_rounded, category: S.current.icons_category_navigation, tags: [S.current.icons_tags_assistant, S.current.icons_tags_direction], iconId: 143),
    IconInfo(icon: Icons.assistant_photo_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_assistant, S.current.icons_tags_photo], iconId: 144),
    IconInfo(icon: Icons.attribution_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_attribution, S.current.icons_tags_credit], iconId: 145),
    IconInfo(icon: Icons.auto_awesome_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_auto, S.current.icons_tags_awesome], iconId: 147),
    IconInfo(icon: Icons.auto_awesome_mosaic_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_auto, S.current.icons_tags_mosaic], iconId: 148),
    IconInfo(icon: Icons.auto_awesome_motion_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_auto, S.current.icons_tags_motion], iconId: 149),
    IconInfo(icon: Icons.auto_delete_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_auto, S.current.icons_tags_delete], iconId: 150),
    IconInfo(icon: Icons.autorenew_rounded, category: S.current.icons_category_action, tags: [S.current.icons_tags_auto, S.current.icons_tags_renew], iconId: 151),
    IconInfo(icon: Icons.av_timer_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_av, S.current.icons_tags_timer], iconId: 152),
    IconInfo(icon: Icons.back_hand_rounded, category: S.current.icons_category_gesture, tags: [S.current.icons_tags_back, S.current.icons_tags_hand], iconId: 153),
    IconInfo(icon: Icons.backpack_rounded, category: S.current.icons_category_travel, tags: [S.current.icons_tags_backpack, S.current.icons_category_travel], iconId: 154),
    IconInfo(icon: Icons.backspace_rounded, category: S.current.icons_category_action, tags: [S.current.icons_tags_backspace, S.current.icons_tags_delete], iconId: 155),
    IconInfo(icon: Icons.bakery_dining_rounded, category: S.current.icons_category_food, tags: [S.current.icons_tags_bakery, S.current.icons_tags_dining], iconId: 156),
    IconInfo(icon: Icons.balcony_rounded, category: S.current.icons_category_building, tags: [S.current.icons_tags_balcony, S.current.icons_tags_outdoor], iconId: 157),
    IconInfo(icon: Icons.bathtub_rounded, category: S.current.icons_category_bathroom, tags: [S.current.icons_tags_bathtub, S.current.icons_tags_relax], iconId: 158),
    IconInfo(icon: Icons.battery_full_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_battery, S.current.icons_tags_full], iconId: 159),
    IconInfo(icon: Icons.battery_std_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_battery, S.current.icons_tags_standard], iconId: 160),
    IconInfo(icon: Icons.battery_unknown_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_battery, S.current.icons_tags_unknown], iconId: 161),
    IconInfo(icon: Icons.bed_rounded, category: S.current.icons_category_furniture, tags: [S.current.icons_tags_bed, S.current.icons_category_sleep], iconId: 163),
    IconInfo(icon: Icons.bedtime_rounded, category: S.current.icons_category_sleep, tags: [S.current.icons_tags_bedtime, S.current.icons_category_sleep], iconId: 164),
    IconInfo(icon: Icons.bedtime_off_rounded, category: S.current.icons_category_sleep, tags: [S.current.icons_tags_bedtime, S.current.icons_tags_off], iconId: 165),
    IconInfo(icon: Icons.bento_rounded, category: S.current.icons_category_food, tags: [S.current.icons_tags_bento, S.current.icons_tags_meal], iconId: 166),
    IconInfo(icon: Icons.biotech_rounded, category: S.current.icons_category_science, tags: [S.current.icons_tags_biotech, S.current.icons_category_science], iconId: 167),
    IconInfo(icon: Icons.blender_rounded, category: S.current.icons_category_kitchen, tags: [S.current.icons_tags_blender, S.current.icons_category_kitchen], iconId: 168),
    IconInfo(icon: Icons.block_rounded, category: S.current.icons_category_action, tags: [S.current.icons_tags_block, S.current.icons_tags_stop], iconId: 169),
    IconInfo(icon: Icons.bloodtype_rounded, category: S.current.icons_category_health, tags: [S.current.icons_tags_blood, S.current.icons_tags_type], iconId: 170),
    IconInfo(icon: Icons.bluetooth_connected_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_bluetooth, S.current.icons_tags_wireless], iconId: 171),
    IconInfo(icon: Icons.bluetooth_disabled_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_bluetooth, S.current.icons_tags_wireless], iconId: 172),
    IconInfo(icon: Icons.bluetooth_searching_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_bluetooth, S.current.icons_tags_wireless], iconId: 173),
    IconInfo(icon: Icons.blur_circular_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_blur, S.current.icons_tags_circular], iconId: 174),
    IconInfo(icon: Icons.blur_linear_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_blur, S.current.icons_tags_linear], iconId: 175),
    IconInfo(icon: Icons.blur_off_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_blur, S.current.icons_tags_off], iconId: 176),
    IconInfo(icon: Icons.blur_on_rounded, category: S.current.icons_category_design, tags: [S.current.icons_tags_blur, S.current.icons_tags_on], iconId: 177),
    IconInfo(icon: Icons.bookmark_add_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_bookmark, S.current.icons_tags_add], iconId: 178),
    IconInfo(icon: Icons.bookmark_remove_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_bookmark, S.current.icons_tags_remove], iconId: 179),
    IconInfo(icon: Icons.bookmarks_rounded, category: S.current.icons_category_content, tags: [S.current.icons_tags_bookmarks, S.current.icons_tags_list], iconId: 180),
    IconInfo(icon: Icons.broken_image_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_broken, S.current.icons_tags_image], iconId: 182),
    IconInfo(icon: Icons.browse_gallery_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_browse, S.current.icons_tags_gallery], iconId: 183),
    IconInfo(icon: Icons.bubble_chart_rounded, category: S.current.icons_category_data, tags: [S.current.icons_tags_bubble, S.current.icons_tags_chart], iconId: 184),
    IconInfo(icon: Icons.build_rounded, category: S.current.icons_category_tools, tags: [S.current.icons_tags_build, S.current.icons_tags_construction], iconId: 185),
    IconInfo(icon: Icons.business_center_rounded, category: S.current.icons_category_business, tags: [S.current.icons_category_business, S.current.icons_tags_center], iconId: 186),
    IconInfo(icon: Icons.cabin_rounded, category: S.current.icons_category_building, tags: [S.current.icons_tags_cabin, S.current.icons_category_building], iconId: 187),
    IconInfo(icon: Icons.cable_rounded, category: S.current.icons_category_tech, tags: [S.current.icons_tags_cable, S.current.icons_tags_connection], iconId: 188),
    IconInfo(icon: Icons.calendar_today_rounded, category: S.current.icons_category_time, tags: [S.current.icons_tags_calendar, S.current.icons_tags_today], iconId: 190),
    IconInfo(icon: Icons.calendar_view_day_rounded, category: S.current.icons_category_time, tags: [S.current.icons_tags_calendar, S.current.icons_tags_view, S.current.icons_tags_day], iconId: 191),
    IconInfo(icon: Icons.call_end_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_call, S.current.icons_tags_end], iconId: 192),
    IconInfo(icon: Icons.call_made_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_call, S.current.icons_tags_made], iconId: 193),
    IconInfo(icon: Icons.call_merge_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_call, S.current.icons_tags_merge], iconId: 194),
    IconInfo(icon: Icons.call_missed_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_call, S.current.icons_tags_missed], iconId: 195),
    IconInfo(icon: Icons.call_received_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_call, S.current.icons_tags_received], iconId: 196),
    IconInfo(icon: Icons.call_split_rounded, category: S.current.icons_category_communication, tags: [S.current.icons_tags_call, S.current.icons_tags_split], iconId: 197),
    IconInfo(icon: Icons.camera_enhance_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_camera, S.current.icons_tags_photo], iconId: 198),
    IconInfo(icon: Icons.camera_front_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_camera, S.current.icons_tags_photo], iconId: 199),
    IconInfo(icon: Icons.camera_rear_rounded, category: S.current.icons_category_media, tags: [S.current.icons_tags_camera, S.current.icons_tags_photo], iconId: 200),
  ];

  static IconInfo? getIcon(int iconId) {
    IconInfo? icon = icons.where((icon) => icon.iconId == iconId).firstOrNull;
    if (icon != null) {
      return icon;
    } else {
      return null;
    }
  }
}